import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk, Geist } from "next/font/google";
import Navbar from "./components/Navbar";
import { PomodoroProvider } from "./context/PomodoroContext";
import { SignalProvider } from "./context/SignalContext";
import AmbientBackground from "./components/ui/AmbientBackground";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`bg-[#0B0F1A] text-white ${spaceGrotesk.className} relative min-h-screen flex flex-col`}>
        <PomodoroProvider>
          <SignalProvider>
            <AmbientBackground />
            <div className="relative z-10 flex flex-col flex-1">
              <Navbar />
              {children}
            </div>
          </SignalProvider>
        </PomodoroProvider>
      </body>
    </html>
  );
}
